/** Official AlgoForge '26 teams — used to pre-fill seed form (one per line). */
export const DEFAULT_TEAM_NAMES = [
  'Impic',
  'Paradigm',
  'Shatbhisha',
  'MergeInfinity',
  'Grid9',
  'Pixels',
  'Neural Nomads',
  'Recursion',
  'Underflow',
  'Infinity Loop',
  'Flux',
  'The Iterators',
  'InnovHERS',
  'Team Symmetry',
  'Elite_Coders',
  'LEGITCODER',
  'Zenith',
  'Status 200',
  'Mugiwara',
  'Neural Society',
  'Arka!',
  'Deploy0RDie',
  'Medura',
  'FOUR.js',
] as const;
